name: Deploy to S3 and OpenSearch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://ttp-portal-bucket --exclude ".git/*" --exclude ".github/*"

      - name: Upload files to OpenSearch
        run: |
          for file in $(find . -type f -name '*.json'); do
            filename=$(basename $file)
            curl -X POST "https://vpc-ttpportal-lrysnolxf3dtvnwgchv3xln2py.ap-south-1.es.amazonaws.com/my-index/_doc/$filename" -H "Content-Type: application/json" -d @$file
          done
